title: "[Bug] Issue Title Here"

description: |
  Thank you for reporting this issue! Please provide detailed information about the problem you encountered.

  ### Steps to Reproduce:
  1. Step 1
  2. Step 2
  3. Step 3

  ### Expected Behavior:
  Describe what you expected to happen.

  ### Actual Behavior:
  Describe what actually happened.

  ### Screenshots:
  If applicable, add screenshots to help explain your problem.

labels:
  - bug
